name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Node.js 23.x и 24.x еще не выпущены (на январь 2025)
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' 
        cache-dependency-path: frontend/yarn.lock
 
    - name: Install dependencies
      run: cd frontend && yarn install --non-interactive
      
    - name: Build
      run: cd frontend && yarn build
      
    - name: Run tests
      run: cd frontend && yarn test --run